In [115]:
import numpy as np
import pandas as pd

In [116]:
df = pd.read_csv('ecom_user.csv')
df

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0

In [117]:
df.isnull().sum()

user_id               160
age                   160
gender                160
device_type           160
time_on_site          160
pages_viewed          160
previous_purchases    160
cart_items            160
discount_seen         160
ad_clicked            160
returning_user        160
avg_session_time      160
bounce_rate           160
purchase              160
dtype: int64

In [118]:
df1 = df.dropna()

In [119]:
df1.isnull().sum()

user_id               0
age                   0
gender                0
device_type           0
time_on_site          0
pages_viewed          0
previous_purchases    0
cart_items            0
discount_seen         0
ad_clicked            0
returning_user        0
avg_session_time      0
bounce_rate           0
purchase              0
dtype: int64

In [120]:
df2 = df.dropna(subset=['gender'])

In [121]:
df2.isnull().sum()

user_id               156
age                   156
gender                  0
device_type           157
time_on_site          159
pages_viewed          156
previous_purchases    157
cart_items            156
discount_seen         157
ad_clicked            155
returning_user        157
avg_session_time      157
bounce_rate           158
purchase              156
dtype: int64

In [122]:
df2 = df.dropna(subset=['cart_items','ad_clicked'])

In [123]:
df2.isnull().sum()

user_id               152
age                   154
gender                151
device_type           150
time_on_site          154
pages_viewed          155
previous_purchases    157
cart_items              0
discount_seen         151
ad_clicked              0
returning_user        153
avg_session_time      156
bounce_rate           156
purchase              157
dtype: int64

In [124]:
df.fillna({
    'age':df['age'].mean(),
    'time_on_site':df['time_on_site'].mean(), 
    'pages_viewed':df['pages_viewed'].mean(),
    'previous_purchases':df['previous_purchases'].mean(),
    'cart_items':df['cart_items'].mean(),
    'discount_seen':df['discount_seen'].mean(),
    'ad_clicked':df['ad_clicked'].mean(),
    'returning_user':df['returning_user'].mean(),
    'avg_session_time':df['avg_session_time'].mean(),
    'bounce_rate':df['bounce_rate'].mean(),
    'purchase':df['purchase'].mean(),
    }, inplace=True)

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,0.502296,0.0,6.970000,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.000000,1.0,19.170000,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.000000,1.0,8.870000,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.000000,1.0,15.794999,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.000000,0.0,18.150000,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.000000,1.0,3.010000,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.000000,1.0,27.480000,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.000000,1.0,27.570000,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.000000,0.0,5.780000,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.000000,1.0,8.280000,15.67,1.0

In [125]:
df.isnull().sum()

user_id               160
age                     0
gender                160
device_type           160
time_on_site            0
pages_viewed            0
previous_purchases      0
cart_items              0
discount_seen           0
ad_clicked              0
returning_user          0
avg_session_time        0
bounce_rate             0
purchase                0
dtype: int64

In [126]:
df[df['user_id'].isna()]

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
117,NaN,20.0,Female,Mobile,7.140000,6.0,8.000000,7.00000,0.0,1.0,1.0,10.280000,90.100000,1.0
191,NaN,36.0,Female,Mobile,7.930000,4.0,6.000000,5.00000,1.0,1.0,1.0,9.840000,49.924402,1.0
220,NaN,37.0,Female,Mobile,23.390000,9.0,5.000000,8.00000,0.0,0.0,0.0,34.790000,59.530000,1.0
238,NaN,24.0,Male,Mobile,19.780000,3.0,14.000000,4.53023,0.0,1.0,0.0,25.450000,13.070000,1.0
263,NaN,52.0,Female,Desktop,18.500000,14.0,11.000000,6.00000,1.0,1.0,0.0,15.520000,49.924402,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7724,NaN,35.0,Female,Mobile,16.510000,7.0,4.000000,5.00000,1.0,1.0,1.0,11.070000,44.800000,1.0
7834,NaN,39.0,Female,Desktop,15.714673,4.0,3.000000,0.00000,0.0,1.0,0.0,3.380000,80.000000,0.0
7845,NaN,41.0,Female,Mobile,28.150000,7.0,1.000000,7.00000,1.0,1.0,0.0,33.460000,87.080000,1.0
7874,NaN,33.0,Male,Mobile,1.430000,3.0,6.964158,9.00000,1.0,0.0,0.0,15.794999,4.880000,1.0
7974,NaN,54.0,Female,Mobile,1.160000,14.0,4.000000,1.00000,0.0,1.0,0.0,1.010000,15.300000,1.0

In [127]:
df['gender'].value_counts()

gender
Male      3931
Female    3909
Name: count, dtype: int64

In [128]:
df['gender'] = df['gender'].fillna('Unknown')

In [129]:
df['device_type'].value_counts()

device_type
Mobile     4685
Desktop    2365
Tablet      790
Name: count, dtype: int64

In [130]:
df['device_type'] = df['device_type'].fillna(df['device_type'].mode()[0])

In [131]:
df.isnull().sum()

user_id               160
age                     0
gender                  0
device_type             0
time_on_site            0
pages_viewed            0
previous_purchases      0
cart_items              0
discount_seen           0
ad_clicked              0
returning_user          0
avg_session_time        0
bounce_rate             0
purchase                0
dtype: int64

In [132]:
df.duplicated(subset=['user_id']).sum()

np.int64(159)

In [133]:
df[df['user_id'].duplicated()]

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
191,NaN,36.0,Female,Mobile,7.930000,4.0,6.000000,5.00000,1.0,1.0,1.0,9.840000,49.924402,1.000000
220,NaN,37.0,Female,Mobile,23.390000,9.0,5.000000,8.00000,0.0,0.0,0.0,34.790000,59.530000,1.000000
238,NaN,24.0,Male,Mobile,19.780000,3.0,14.000000,4.53023,0.0,1.0,0.0,25.450000,13.070000,1.000000
263,NaN,52.0,Female,Desktop,18.500000,14.0,11.000000,6.00000,1.0,1.0,0.0,15.520000,49.924402,1.000000
296,NaN,38.0,Female,Mobile,11.870000,19.0,8.000000,8.00000,1.0,1.0,1.0,8.580000,80.780000,0.998342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7724,NaN,35.0,Female,Mobile,16.510000,7.0,4.000000,5.00000,1.0,1.0,1.0,11.070000,44.800000,1.000000
7834,NaN,39.0,Female,Desktop,15.714673,4.0,3.000000,0.00000,0.0,1.0,0.0,3.380000,80.000000,0.000000
7845,NaN,41.0,Female,Mobile,28.150000,7.0,1.000000,7.00000,1.0,1.0,0.0,33.460000,87.080000,1.000000
7874,NaN,33.0,Male,Mobile,1.430000,3.0,6.964158,9.00000,1.0,0.0,0.0,15.794999,4.880000,1.000000
7974,NaN,54.0,Female,Mobile,1.160000,14.0,4.000000,1.00000,0.0,1.0,0.0,1.010000,15.300000,1.000000

In [134]:
df.drop_duplicates(subset=['user_id'],inplace=True)

In [135]:
df.isnull().sum()

user_id               1
age                   0
gender                0
device_type           0
time_on_site          0
pages_viewed          0
previous_purchases    0
cart_items            0
discount_seen         0
ad_clicked            0
returning_user        0
avg_session_time      0
bounce_rate           0
purchase              0
dtype: int64

In [136]:
df.isnull().sum()

user_id               1
age                   0
gender                0
device_type           0
time_on_site          0
pages_viewed          0
previous_purchases    0
cart_items            0
discount_seen         0
ad_clicked            0
returning_user        0
avg_session_time      0
bounce_rate           0
purchase              0
dtype: int64

In [138]:
df = df.dropna()

In [140]:
df.isnull().sum()

user_id               0
age                   0
gender                0
device_type           0
time_on_site          0
pages_viewed          0
previous_purchases    0
cart_items            0
discount_seen         0
ad_clicked            0
returning_user        0
avg_session_time      0
bounce_rate           0
purchase              0
dtype: int64

In [139]:
df

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,0.502296,0.0,6.970000,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.000000,1.0,19.170000,86.73,1.0
2,3.0,32.0,Female,Mobile,11.64,12.0,11.0,0.0,0.0,0.000000,1.0,8.870000,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.000000,1.0,15.794999,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.000000,0.0,18.150000,55.35,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.000000,1.0,3.010000,82.44,1.0
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.000000,1.0,27.480000,10.06,1.0
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.000000,1.0,27.570000,21.34,1.0
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.000000,0.0,5.780000,2.03,1.0
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.000000,1.0,8.280000,15.67,1.0

In [145]:
df.rename(columns={'age':'user_age'}, inplace=True)

In [146]:
df.head()

,user_id,user_age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,0.502296,0.0,6.970000,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.000000,1.0,19.170000,86.73,1.0
2,3.0,32.0,Female,Mobile,11.64,12.0,11.0,0.0,0.0,0.000000,1.0,8.870000,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.000000,1.0,15.794999,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.000000,0.0,18.150000,55.35,1.0

In [149]:
df.columns = df.columns.str.title()

In [150]:
df.head()

,User_Id,User_Age,Gender,Device_Type,Time_On_Site,Pages_Viewed,Previous_Purchases,Cart_Items,Discount_Seen,Ad_Clicked,Returning_User,Avg_Session_Time,Bounce_Rate,Purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,0.502296,0.0,6.970000,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.000000,1.0,19.170000,86.73,1.0
2,3.0,32.0,Female,Mobile,11.64,12.0,11.0,0.0,0.0,0.000000,1.0,8.870000,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.000000,1.0,15.794999,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.000000,0.0,18.150000,55.35,1.0