In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('netflix_users.csv')
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [23]:
df.groupby('Country')['Age'].mean()

Country
Australia    47.129668
Brazil       46.826209
Canada       46.922490
France       46.336433
Germany      46.372595
India        46.332934
Japan        46.233211
Mexico       46.452066
UK           46.405093
USA          45.835797
Name: Age, dtype: float64

In [24]:
df.groupby('Country')['Watch_Time_Hours'].max()

Country
Australia    999.73
Brazil       999.96
Canada       999.99
France       999.20
Germany      999.75
India        999.05
Japan        999.18
Mexico       999.73
UK           999.72
USA          998.93
Name: Watch_Time_Hours, dtype: float64

In [25]:
df.groupby('Favorite_Genre')['Watch_Time_Hours'].sum()

Favorite_Genre
Action         1789099.14
Comedy         1787154.64
Documentary    1820526.54
Drama          1782336.40
Horror         1806967.49
Romance        1810646.62
Sci-Fi         1714990.62
Name: Watch_Time_Hours, dtype: float64

In [26]:
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [27]:
df.groupby(['Country','Subscription_Type'])['Watch_Time_Hours'].sum()

Country    Subscription_Type
Australia  Basic                403000.79
           Premium              417391.23
           Standard             418108.77
Brazil     Basic                420881.37
           Premium              435782.91
           Standard             404727.09
Canada     Basic                415457.16
           Premium              420578.65
           Standard             437408.06
France     Basic                440554.47
           Premium              414300.77
           Standard             396579.82
Germany    Basic                407778.76
           Premium              440903.20
           Standard             410983.43
India      Basic                425360.19
           Premium              400344.28
           Standard             407363.05
Japan      Basic                402161.06
           Premium              414292.73
           Standard             399320.71
Mexico     Basic                418007.59
           Premium              424703.92
           Standard             395032.72
UK         Basic                444708.58
           Premium              414955.15
           Standard             426136.94
USA        Basic                425113.05
           Premium              429588.83
           Standard             400196.17
Name: Watch_Time_Hours, dtype: float64

In [28]:
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [29]:
df.groupby('Country')[['Age','Watch_Time_Hours']].max()

           Age  Watch_Time_Hours
Country
Australia   80            999.73
Brazil      80            999.96
Canada      80            999.99
France      80            999.20
Germany     80            999.75
India       80            999.05
Japan       80            999.18
Mexico      80            999.73
UK          80            999.72
USA         80            998.93

In [30]:
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [31]:
df.groupby('Country').agg({
    'Age':['max','min'],
    'Watch_Time_Hours':'sum'
})

          Age     Watch_Time_Hours
          max min              sum
Country
Australia  80  13       1238500.79
Brazil     80  13       1261391.37
Canada     80  13       1273443.87
France     80  13       1251435.06
Germany    80  13       1259665.39
India      80  13       1233067.52
Japan      80  13       1215774.50
Mexico     80  13       1237744.23
UK         80  13       1285800.67
USA        80  13       1254898.05

In [32]:
country_agg = df.groupby('Country').agg(
    Max_Age=('Age','max'),
    Min_Age=('Age','min'),
    Total_Watch_Time=('Watch_Time_Hours','sum')
)

In [33]:
country_agg

           Max_Age  Min_Age  Total_Watch_Time
Country
Australia       80       13        1238500.79
Brazil          80       13        1261391.37
Canada          80       13        1273443.87
France          80       13        1251435.06
Germany         80       13        1259665.39
India           80       13        1233067.52
Japan           80       13        1215774.50
Mexico          80       13        1237744.23
UK              80       13        1285800.67
USA             80       13        1254898.05