In [1]:
import numpy as np
import pandas as pd

In [5]:
pd.Series([23,45,67,89])

0    23
1    45
2    67
3    89
dtype: int64

In [6]:
pd.Series([45, 67, 89, 90],index=["Vansh", "Rahul", "Aman", "Kartik"])

Vansh     45
Rahul     67
Aman      89
Kartik    90
dtype: int64

In [7]:
data = {"Vansh":45, "Rahul":67, "Aman":89, "Kartik":90}
pd.Series(data)

Vansh     45
Rahul     67
Aman      89
Kartik    90
dtype: int64

In [8]:
data = {
    'Name':['Vansh','Aman','Rahul','Kartik'],
    'Score':[23, 45, 78, 90],
}

pd.DataFrame(data)

     Name  Score
0   Vansh     23
1    Aman     45
2   Rahul     78
3  Kartik     90

In [2]:
data = pd.read_csv('netflix_users.csv')
data

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14
...,...,...,...,...,...,...,...,...
24995,24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12

In [10]:
data.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [11]:
data.head(10)

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14
5,6,David Johnson,21,USA,Standard,615.93,Romance,2025-02-03
6,7,John Hernandez,57,Canada,Standard,755.47,Romance,2025-01-05
7,8,Katie Hernandez,68,USA,Standard,145.23,Sci-Fi,2024-10-30
8,9,James Williams,39,UK,Basic,950.14,Action,2024-04-16
9,10,Alex Davis,55,Mexico,Standard,696.66,Horror,2024-07-03

In [12]:
data.tail()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
24995,24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12

In [13]:
data.tail(10)

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
24990,24991,Chris Miller,52,Brazil,Basic,476.63,Horror,2024-05-25
24991,24992,Sarah Williams,43,Germany,Standard,361.23,Sci-Fi,2025-01-26
24992,24993,James Brown,47,India,Standard,411.40,Documentary,2024-03-15
24993,24994,Alex Martinez,22,Brazil,Basic,486.92,Documentary,2024-06-18
24994,24995,Jane Miller,76,USA,Standard,47.74,Horror,2024-08-14
24995,24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12

In [16]:
data.sample()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
21493,21494,Jane Davis,71,France,Basic,644.67,Comedy,2024-05-23

In [17]:
data.shape

(25000, 8)

In [18]:
data.dtypes

User_ID                int64
Name                     str
Age                    int64
Country                  str
Subscription_Type        str
Watch_Time_Hours     float64
Favorite_Genre           str
Last_Login               str
dtype: object

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  str
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  str
 4   Subscription_Type  25000 non-null  str
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  str
 7   Last_Login         25000 non-null  str
dtypes: float64(1), int64(2), str(5)
memory usage: 1.5 MB

In [20]:
data.describe()

            User_ID           Age  Watch_Time_Hours
count  25000.000000  25000.000000      25000.000000
mean   12500.500000     46.482880        500.468858
std     7217.022701     19.594861        286.381815
min        1.000000     13.000000          0.120000
25%     6250.750000     29.000000        256.567500
50%    12500.500000     46.000000        501.505000
75%    18750.250000     63.000000        745.732500
max    25000.000000     80.000000        999.990000

In [23]:
data.isnull().sum()

User_ID              0
Name                 0
Age                  0
Country              0
Subscription_Type    0
Watch_Time_Hours     0
Favorite_Genre       0
Last_Login           0
dtype: int64