In [32]:
import numpy as np
import pandas as pd

In [33]:
data = pd.read_csv('netflix_users.csv')
data

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14
...,...,...,...,...,...,...,...,...
24995,24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29
24997,24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16
24998,24999,Michael Williams,71,USA,Basic,655.89,Action,2024-08-27
24999,25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12

In [34]:
data['Name'].head()

0    James Martinez
1       John Miller
2        Emma Davis
3       Emma Miller
4        Jane Smith
Name: Name, dtype: str

In [35]:
data[['Name','Age']].head()

             Name  Age
0  James Martinez   18
1     John Miller   23
2      Emma Davis   60
3     Emma Miller   44
4      Jane Smith   68

In [36]:
data = data.set_index('User_ID')

In [37]:
data.head()

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [38]:
data.loc[1]

Name                 James Martinez
Age                              18
Country                      France
Subscription_Type           Premium
Watch_Time_Hours              80.26
Favorite_Genre                Drama
Last_Login               2024-05-12
Name: 1, dtype: object

In [39]:
data.loc[[1,2]]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05

In [40]:
data.loc[1:5]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [41]:
data.iloc[0]

Name                 James Martinez
Age                              18
Country                      France
Subscription_Type           Premium
Watch_Time_Hours              80.26
Favorite_Genre                Drama
Last_Login               2024-05-12
Name: 1, dtype: object

In [42]:
data.iloc[[0,1]]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05

In [43]:
data.iloc[0:5]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [44]:
data.iloc[0:5][['Name', 'Age', 'Last_Login']]

                   Name  Age  Last_Login
User_ID
1        James Martinez   18  2024-05-12
2           John Miller   23  2025-02-05
3            Emma Davis   60  2025-01-24
4           Emma Miller   44  2024-03-25
5            Jane Smith   68  2025-01-14

In [47]:
data[data['Age'] < 18].head()

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
27,James Jones,17,Mexico,Standard,253.60,Documentary,2024-09-29
31,Chris Jones,14,Germany,Premium,81.89,Drama,2024-08-06
40,Sarah Hernandez,15,Brazil,Premium,914.70,Horror,2024-04-30
47,Sarah Smith,16,Brazil,Premium,321.21,Documentary,2024-04-13
56,Alex Davis,16,Mexico,Premium,739.71,Sci-Fi,2024-08-11

In [48]:
data['Age'] > 18

User_ID
1        False
2         True
3         True
4         True
5         True
         ...
24996    False
24997    False
24998    False
24999     True
25000     True
Name: Age, Length: 25000, dtype: bool

In [49]:
data.head()

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [ ]:
data[(data['Watch_Time_Hours'] > 100) & (data['Age'] < 18)]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
27,James Jones,17,Mexico,Standard,253.60,Documentary,2024-09-29
40,Sarah Hernandez,15,Brazil,Premium,914.70,Horror,2024-04-30
47,Sarah Smith,16,Brazil,Premium,321.21,Documentary,2024-04-13
56,Alex Davis,16,Mexico,Premium,739.71,Sci-Fi,2024-08-11
109,Sarah Martinez,17,Australia,Standard,978.84,Comedy,2025-02-27
...,...,...,...,...,...,...,...
24936,James Davis,13,France,Standard,670.46,Sci-Fi,2024-04-25
24938,Chris Williams,17,Mexico,Basic,838.60,Horror,2024-10-08
24986,Chris Miller,17,France,Basic,579.39,Comedy,2024-07-03
24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29
24998,Sarah Miller,14,USA,Premium,351.80,Action,2024-10-16

In [54]:
data[(data['Watch_Time_Hours'] > 100) & (data['Age'] < 18)][['Name','Watch_Time_Hours','Country']]

                    Name  Watch_Time_Hours    Country
User_ID
27           James Jones            253.60     Mexico
40       Sarah Hernandez            914.70     Brazil
47           Sarah Smith            321.21     Brazil
56            Alex Davis            739.71     Mexico
109       Sarah Martinez            978.84  Australia
...                  ...               ...        ...
24936        James Davis            670.46     France
24938     Chris Williams            838.60     Mexico
24986       Chris Miller            579.39     France
24997        Jane Miller            112.37        USA
24998       Sarah Miller            351.80        USA

[1602 rows x 3 columns]

In [59]:
data[data['Country'] == 'Brazil'].count()

Name                 2503
Age                  2503
Country              2503
Subscription_Type    2503
Watch_Time_Hours     2503
Favorite_Genre       2503
Last_Login           2503
dtype: int64

In [62]:
data[ ~ (data['Country'] == 'USA')]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
7,John Hernandez,57,Canada,Standard,755.47,Romance,2025-01-05
9,James Williams,39,UK,Basic,950.14,Action,2024-04-16
10,Alex Davis,55,Mexico,Standard,696.66,Horror,2024-07-03
...,...,...,...,...,...,...,...
24992,Sarah Williams,43,Germany,Standard,361.23,Sci-Fi,2025-01-26
24993,James Brown,47,India,Standard,411.40,Documentary,2024-03-15
24994,Alex Martinez,22,Brazil,Basic,486.92,Documentary,2024-06-18
24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
25000,James Jones,19,Germany,Premium,207.06,Documentary,2024-04-12

In [63]:
data[data['Country'].isin(['India','UK'])]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
9,James Williams,39,UK,Basic,950.14,Action,2024-04-16
17,Chris Davis,74,UK,Standard,610.70,Drama,2024-07-03
22,James Martinez,46,UK,Premium,620.74,Comedy,2024-04-19
23,Sarah Davis,40,UK,Basic,451.59,Drama,2024-04-08
...,...,...,...,...,...,...,...
24967,James Johnson,34,India,Basic,749.36,Romance,2025-01-22
24969,Chris Hernandez,58,UK,Basic,611.96,Horror,2025-01-04
24983,Michael Williams,74,UK,Standard,502.69,Horror,2025-03-06
24984,John Miller,25,India,Premium,186.35,Drama,2024-09-15
24993,James Brown,47,India,Standard,411.40,Documentary,2024-03-15

In [78]:
data[data['Age'].between(15, 18)]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
27,James Jones,17,Mexico,Standard,253.60,Documentary,2024-09-29
40,Sarah Hernandez,15,Brazil,Premium,914.70,Horror,2024-04-30
47,Sarah Smith,16,Brazil,Premium,321.21,Documentary,2024-04-13
56,Alex Davis,16,Mexico,Premium,739.71,Sci-Fi,2024-08-11
...,...,...,...,...,...,...,...
24930,John Johnson,18,India,Premium,890.72,Comedy,2024-03-19
24938,Chris Williams,17,Mexico,Basic,838.60,Horror,2024-10-08
24986,Chris Miller,17,France,Basic,579.39,Comedy,2024-07-03
24996,David Miller,18,Australia,Premium,183.88,Horror,2025-01-18
24997,Jane Miller,17,USA,Premium,112.37,Drama,2024-06-29

In [77]:
data[data['Name'].str.contains("Davis")]

,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
User_ID,,,,,,,
3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
10,Alex Davis,55,Mexico,Standard,696.66,Horror,2024-07-03
17,Chris Davis,74,UK,Standard,610.70,Drama,2024-07-03
23,Sarah Davis,40,UK,Basic,451.59,Drama,2024-04-08
34,David Davis,56,Mexico,Basic,835.85,Documentary,2024-07-11
...,...,...,...,...,...,...,...
24961,Michael Davis,59,Japan,Basic,183.75,Horror,2024-10-11
24973,Sarah Davis,58,Australia,Standard,310.43,Comedy,2024-09-25
24980,Jane Davis,65,Mexico,Standard,529.50,Romance,2024-03-12
24982,Chris Davis,38,Germany,Premium,696.61,Sci-Fi,2024-08-04
24987,John Davis,55,USA,Premium,812.89,Drama,2025-02-20

In [81]:
data['Country']

User_ID
1           France
2              USA
3               UK
4              USA
5              USA
           ...
24996    Australia
24997          USA
24998          USA
24999          USA
25000      Germany
Name: Country, Length: 25000, dtype: str

In [82]:
data[['Country']]

           Country
User_ID
1           France
2              USA
3               UK
4              USA
5              USA
...            ...
24996    Australia
24997          USA
24998          USA
24999          USA
25000      Germany

[25000 rows x 1 columns]