In [1]:
import numpy as np
import pandas as pd

In [46]:
df = pd.read_csv('netflix_users.csv')
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [5]:
age_sorted_df = df.sort_values(by='Age')
age_sorted_df

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
2515,2516,John Hernandez,13,France,Basic,405.24,Sci-Fi,2024-09-23
16822,16823,Michael Hernandez,13,Brazil,Premium,164.45,Horror,2024-03-10
16816,16817,Emma Miller,13,Brazil,Basic,743.85,Sci-Fi,2025-02-12
21895,21896,Alex Martinez,13,Germany,Premium,439.14,Comedy,2024-07-08
7698,7699,Katie Williams,13,France,Basic,810.10,Drama,2024-11-10
...,...,...,...,...,...,...,...,...
16096,16097,James Johnson,80,UK,Basic,919.44,Documentary,2024-10-23
23277,23278,Alex Smith,80,UK,Basic,608.68,Horror,2025-02-20
15517,15518,John Davis,80,Australia,Standard,483.74,Horror,2024-04-08
2096,2097,Sarah Williams,80,Germany,Basic,732.50,Horror,2024-12-08
5439,5440,Katie Jones,80,Mexico,Premium,723.21,Action,2024-12-13

In [6]:
time_sorted_df = df.sort_values(by='Watch_Time_Hours', ascending=False)
time_sorted_df

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27
...,...,...,...,...,...,...,...,...
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29

In [7]:
country_time_sorted_df = df.sort_values(by=['Country','Watch_Time_Hours'])

In [32]:
country_time_sorted_df

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29
24353,24354,Alex Hernandez,27,Australia,Premium,0.31,Sci-Fi,2024-06-03
3706,3707,Alex Brown,24,Australia,Basic,0.57,Drama,2024-10-07
376,377,Katie Miller,27,Australia,Basic,1.33,Drama,2024-11-18
21582,21583,Katie Jones,62,Australia,Premium,2.35,Romance,2024-06-01
...,...,...,...,...,...,...,...,...
11225,11226,Jane Martinez,33,USA,Basic,998.21,Comedy,2024-07-26
317,318,Jane Johnson,64,USA,Basic,998.40,Comedy,2024-08-10
23278,23279,Chris Miller,17,USA,Basic,998.72,Documentary,2024-11-11
7114,7115,Alex Garcia,26,USA,Premium,998.92,Drama,2024-09-11
11233,11234,Sarah Garcia,38,USA,Standard,998.93,Documentary,2024-11-27

In [33]:
country_time_sorted_df = df.sort_values(by=['Country','Watch_Time_Hours'], ascending=[True, False])

In [34]:
country_time_sorted_df

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27
7086,7087,Michael Smith,70,Australia,Standard,999.32,Documentary,2024-03-29
3611,3612,Katie Smith,55,Australia,Basic,999.27,Horror,2025-02-11
20194,20195,Chris Smith,18,Australia,Basic,999.25,Drama,2024-12-14
12213,12214,Michael Williams,34,Australia,Premium,999.18,Romance,2024-08-25
...,...,...,...,...,...,...,...,...
3072,3073,Katie Johnson,54,USA,Premium,1.48,Drama,2024-06-16
777,778,James Smith,53,USA,Standard,1.22,Drama,2024-12-23
10702,10703,Chris Jones,60,USA,Basic,0.83,Comedy,2024-05-02
4020,4021,Michael Williams,66,USA,Premium,0.47,Comedy,2024-09-02
3563,3564,Alex Davis,39,USA,Standard,0.36,Drama,2024-09-03

In [44]:
df['Watch_Rank'] = df['Watch_Time_Hours'].rank()

In [45]:
df.sort_values(by='Watch_Rank')

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29,1.0
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23,2.0
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31,3.0
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18,4.0
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12,5.5
...,...,...,...,...,...,...,...,...,...
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27,24995.5
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07,24997.0
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26,24998.0
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10,24999.0
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14,25000.0

In [47]:
df['Watch_Rank'] = df['Watch_Time_Hours'].rank(method="min")

In [48]:
df.sort_values(by='Watch_Rank')

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29,1.0
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23,2.0
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31,3.0
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18,4.0
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12,5.0
...,...,...,...,...,...,...,...,...,...
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27,24995.0
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07,24997.0
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26,24998.0
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10,24999.0
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14,25000.0

In [40]:
df['Watch_Rank'] = df['Watch_Time_Hours'].rank(method="max")

In [41]:
df.sort_values(by='Watch_Rank')

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29,1.0
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23,2.0
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31,3.0
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18,4.0
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12,6.0
...,...,...,...,...,...,...,...,...,...
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27,24996.0
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07,24997.0
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26,24998.0
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10,24999.0
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14,25000.0

In [42]:
df['Watch_Rank'] = df['Watch_Time_Hours'].rank(method="dense")

In [43]:
df.sort_values(by='Watch_Rank')

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29,1.0
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23,2.0
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31,3.0
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18,4.0
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12,5.0
...,...,...,...,...,...,...,...,...,...
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27,22083.0
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07,22084.0
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26,22085.0
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10,22086.0
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14,22087.0

In [49]:
df.nlargest(5, "Watch_Time_Hours")

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
3940,3941,Chris Brown,70,Canada,Standard,999.99,Romance,2025-02-14,25000.0
21372,21373,Chris Johnson,62,Brazil,Premium,999.96,Action,2024-05-10,24999.0
23705,23706,Chris Miller,52,Brazil,Basic,999.87,Romance,2024-10-26,24998.0
11588,11589,Chris Martinez,55,Germany,Premium,999.75,Horror,2025-02-07,24997.0
6406,6407,Alex Martinez,52,Australia,Premium,999.73,Drama,2024-06-27,24995.0

In [50]:
df.nsmallest(5, "Watch_Time_Hours")

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login,Watch_Rank
20477,20478,Alex Johnson,46,Australia,Premium,0.12,Comedy,2024-10-29,1.0
355,356,Sarah Garcia,72,France,Standard,0.22,Comedy,2024-09-23,2.0
19667,19668,Katie Brown,51,Germany,Premium,0.24,Horror,2024-10-31,3.0
17274,17275,Alex Smith,25,Japan,Standard,0.26,Drama,2024-05-18,4.0
3332,3333,Katie Johnson,27,Japan,Standard,0.29,Romance,2024-06-12,5.0